# site settings
title: Perspective
subtitle: by Divyanshu
email: dvyanshu0@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://divyansh-u5.github.io/ # the base hostname & protocol for your site
author: Divyanshu Sharma
street_address: Puranpur Road,Near Khalsa Dharam Kanta
city: Pilibhit
state: Uttar Pradesh
zip_code: 262001
country: India
phone: +91-6395364286

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://divyansh-u5.github.io/
  Instagram: https://www.instagram.com/dev2divyanshu/?hl=en
  LinkedIn: https://www.linkedin.com/in/divyanshu-sharma-46a2a1364/




# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
